### ISSUE TITLE
请问作者前端是不是缺一些文件？

### ISSUE THREAD

**Issue by tesla1060** [ioiogoo/Vue-News-Board#1]
按照下面的步骤运行，发现找不到build/dev_server.js

    # install dependencies
    npm install

    # serve with hot reload at localhost:8080
    npm run dev

好像webpack 要generate的js文件也没有出来。

**Comment by ioiogoo** [comment]
所有代码和生产环境下相同，可能是你的使用姿势不对

**Comment by tesla1060** [comment]
@ioiogoo 你好，好像前端webpack里的build文件夹确实不在啊。

**Comment by ioiogoo** [comment]
@tesla1060  我刚看了下，确实没有build这个文件夹，因为我在.gitignore文件把build给屏蔽了，之前大意了，现在我已经重新上传了build这个文件夹。
