### ISSUE TITLE
前端能否自动刷新

### ISSUE THREAD

**Issue by royburns** [ioiogoo/Vue-News-Board#2]
### 如题

**Comment by ioiogoo** [comment]
有刷新按钮的

**Comment by royburns** [comment]
嗯那个按钮知道，只是觉得如果自动刷新会不会更好？哈哈哈，只是提个建议
另外，如果要做自动化刷新，是在前端做？还是也需要后端支持

**Comment by ioiogoo** [comment]
前后端都要支持，请参考[Readhub](https://readhub.cn/)

**Comment by royburns** [comment]
好的，多谢
